@extends('layouts.app')
@section('title', 'Departamentos')
@section('header', 'Departamentos')
@section('content')
<div class="mx-auto grid max-w-7xl gap-7">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="ui-page-kicker">Administração</p><h1 class="mt-1 ui-page-title">Departamentos</h1><p class="mt-2 ui-page-copy">Categorias gerais da área. Departamentos não concedem nem restringem acesso.</p></div>@can('create', App\Models\Department::class)<a class="ui-button-primary" href="{{ route('departments.create') }}">Novo departamento</a>@endcan</header>
    <section class="ui-card overflow-hidden">
        <form class="grid gap-3 border-b border-border-default bg-surface-muted/60 p-5 sm:grid-cols-[1fr_13rem_auto]" method="GET"><div><label class="sr-only" for="search">Buscar</label><input class="ui-input" id="search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Nome ou descrição"></div><div><label class="sr-only" for="status">Status</label><select class="ui-select" id="status" name="status"><option value="">Todos os status</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Ativos</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inativos</option></select></div><button class="ui-button-primary" type="submit">Filtrar</button></form>
        <div class="divide-y divide-border-default">@forelse($departments as $department)<article class="grid gap-4 p-5 sm:grid-cols-[minmax(0,1fr)_9rem_9rem_auto] sm:items-center"><div><h2 class="font-semibold text-text-primary">{{ $department->name }}</h2><p class="mt-1 text-sm text-text-secondary">{{ $department->description ?: 'Sem descrição' }}</p></div><p class="text-sm text-text-secondary"><strong class="text-text-primary">{{ $department->positions_count }}</strong> cargos</p><p class="text-sm text-text-secondary"><strong class="text-text-primary">{{ $department->members_count }}</strong> membros</p><div class="flex flex-wrap items-center gap-2"><x-status-badge :status="$department->status"/>@can('update', $department)<a class="ui-button-outline px-3 py-2 text-xs" href="{{ route('departments.edit', $department) }}">Editar</a><form method="POST" action="{{ route('departments.status', $department) }}" data-confirm="{{ $department->status === App\Status::Active ? 'Inativar este departamento? Os cargos existentes serão preservados.' : 'Ativar este departamento?' }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $department->status === App\Status::Active ? 'inactive' : 'active' }}"><button @class(['ui-button-danger px-3 py-2 text-xs' => $department->status === App\Status::Active, 'ui-button-secondary px-3 py-2 text-xs' => $department->status !== App\Status::Active])>{{ $department->status === App\Status::Active ? 'Inativar' : 'Ativar' }}</button></form>@endcan</div></article>@empty<p class="p-12 text-center text-sm text-text-secondary">Nenhum departamento encontrado.</p>@endforelse</div>
        <div class="p-4">{{ $departments->links() }}</div>
    </section>
</div>
@endsection
