@extends('layouts.app')
@section('title', 'Novo usuário')
@section('header', 'Novo usuário')
@section('content')
<div class="mx-auto grid max-w-4xl gap-6"><a class="text-sm font-semibold text-brand-primary" href="{{ route('users.index') }}">← Voltar para usuários</a><header><p class="ui-page-kicker">Administração</p><h1 class="mt-1 ui-page-title">Transformar membro em usuário</h1><p class="mt-2 ui-page-copy">As igrejas e permissões são herdadas automaticamente dos cargos ativos.</p></header>
@if($errors->any())<div class="ui-alert-error" role="alert"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="ui-card grid gap-6 p-6 sm:p-8" method="POST" action="{{ route('users.store') }}">@csrf
    <fieldset><legend class="ui-label">Membro elegível</legend><div class="mt-2 grid gap-3">@forelse($members as $item)@php($member = $item['member'])<label class="cursor-pointer rounded-2xl border border-border-default p-4 transition has-checked:border-brand-primary has-checked:bg-brand-primary-soft"><span class="flex items-start gap-3"><input class="mt-1 size-4 accent-brand-primary" type="radio" name="member_id" value="{{ $member->id }}" @checked(old('member_id', request('member_id')) === $member->id) required><span><strong class="block text-text-primary">{{ $member->name }}</strong><span class="mt-1 block text-sm text-text-secondary">@foreach($item['assignments'] as $assignment){{ $assignment->membership->church->name }} · {{ $assignment->position->name }}{{ $assignment->position->department ? ' / '.$assignment->position->department->name : '' }}{{ !$loop->last ? '; ' : '' }}@endforeach</span><span class="mt-1 block text-xs text-text-secondary">Permissões efetivas: {{ $item['assignments']->flatMap(fn ($assignment) => $assignment->position->permissions)->pluck('permissionModule.name')->unique()->join(', ') ?: 'nenhuma configurada' }}</span></span></span></label>@empty<p class="rounded-2xl bg-surface-muted p-5 text-sm text-text-secondary">Não há membros sem usuário que possuam cargo válido para acesso. Atribua primeiro um cargo na tela do membro.</p>@endforelse</div></fieldset>
    <div><label class="ui-label" for="username">Username</label><input class="ui-input" id="username" name="username" value="{{ old('username') }}" minlength="3" maxlength="50" pattern="[a-z0-9._-]+" autocomplete="off" required><p class="mt-1 text-xs text-text-secondary">3 a 50 caracteres: letras minúsculas sem acento, números, ponto, hífen e sublinhado.</p></div>
    <div class="rounded-2xl bg-info-soft p-4 text-sm text-text-secondary">Uma senha temporária segura será mostrada apenas uma vez depois da criação. Somente o hash será armazenado.</div>
    <div class="flex justify-end gap-3"><a class="ui-button-outline" href="{{ route('users.index') }}">Cancelar</a><button class="ui-button-primary" @disabled($members->isEmpty())>Criar usuário</button></div>
</form></div>
@endsection
