@extends('layouts.app')
@section('title', 'Usuários')
@section('header', 'Usuários')
@section('content')
<div class="mx-auto grid max-w-7xl gap-7">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="ui-page-kicker">Administração</p><h1 class="mt-1 ui-page-title">Usuários</h1><p class="mt-2 ui-page-copy">Contas de acesso vinculadas a membros e às permissões herdadas de seus cargos.</p></div>@can('create', App\Models\User::class)<a class="ui-button-primary" href="{{ route('users.create') }}">Novo usuário</a>@endcan</header>
    <section class="ui-card overflow-hidden"><form class="grid gap-3 border-b border-border-default bg-surface-muted/60 p-5 sm:grid-cols-2 lg:grid-cols-[1fr_12rem_15rem_auto]" method="GET"><input class="ui-input" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Nome ou username" aria-label="Buscar usuário"><select class="ui-select" name="status" aria-label="Status"><option value="">Todos os status</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Ativos</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inativos</option></select><select class="ui-select" name="church_id" aria-label="Igreja"><option value="">Igreja ativa</option>@foreach($churches as $church)<option value="{{ $church->id }}" @selected(($selectedChurch?->id ?? null) === $church->id)>{{ $church->name }}</option>@endforeach</select><button class="ui-button-primary">Filtrar</button></form>
        <div class="divide-y divide-border-default">@forelse($users as $user)@php($activeAssignments = $user->member?->memberships->flatMap(fn ($membership) => $membership->positionAssignments)->filter(fn($assignment) => $assignment->status === App\Status::Active && $assignment->started_at->lte(today()) && ($assignment->ended_at === null || $assignment->ended_at->gte(today())) && $assignment->position->status === App\Status::Active && $assignment->position->grants_system_access) ?? collect())<article class="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_minmax(15rem,1fr)_auto] lg:items-center"><div><h2 class="font-semibold text-text-primary">{{ $user->member?->name ?? $user->display_name }}</h2><p class="mt-1 text-sm text-text-secondary">{{ '@'.$user->username }} · {{ $user->is_global_administrator ? 'Escopo global' : ($activeAssignments->pluck('membership.church.name')->unique()->join(', ') ?: 'Sem acesso válido') }}</p><p class="mt-1 text-xs text-text-secondary">{{ $user->must_change_password ? 'Troca de senha obrigatória' : 'Senha regular' }} · Último login: {{ $user->last_login_at?->format('d/m/Y H:i') ?? 'Nunca' }}</p></div><div><p class="text-xs font-semibold text-text-secondary uppercase">Cargos herdados</p><p class="mt-1 text-sm text-text-secondary">{{ $user->is_global_administrator ? 'Administrador global' : ($activeAssignments->map(fn($assignment) => $assignment->position->name.($assignment->position->department ? ' · '.$assignment->position->department->name : ''))->unique()->join(', ') ?: 'Nenhum') }}</p></div><div class="flex items-center gap-3"><x-status-badge :status="$user->status"/><a class="ui-button-outline px-3 py-2 text-xs" href="{{ route('users.show', $user) }}">Detalhes</a></div></article>@empty<p class="p-12 text-center text-sm text-text-secondary">Nenhum usuário encontrado.</p>@endforelse</div><div class="p-4">{{ $users->links() }}</div>
    </section>
</div>
@endsection
