@extends('layouts.app')
@section('title', 'Detalhes do usuário')
@section('header', 'Detalhes do usuário')
@section('content')
<div class="mx-auto grid max-w-5xl gap-6"><a class="text-sm font-semibold text-brand-primary" href="{{ route('users.index') }}">← Voltar para usuários</a>
@if($temporaryPassword)<section class="rounded-2xl border border-warning/20 bg-warning-soft p-5 text-warning" role="status"><strong>Senha temporária — copie agora:</strong><code class="ml-2 rounded bg-surface-card px-2 py-1 text-text-primary">{{ $temporaryPassword }}</code><p class="mt-2 text-sm">Ela está somente nesta resposta e não será exibida novamente.</p></section>@endif
<header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="ui-page-kicker">Administração</p><h1 class="mt-1 ui-page-title">{{ $user->member?->name ?? $user->display_name }}</h1><p class="mt-2 text-sm text-text-secondary">{{ '@'.$user->username }}</p></div><div class="flex items-center gap-3"><x-status-badge :status="$user->status"/>@if($user->must_change_password)<span class="rounded-full bg-warning-soft px-3 py-1 text-xs font-semibold text-warning">Troca obrigatória</span>@endif</div></header>
<section class="ui-card p-6 sm:p-8"><h2 class="text-lg font-semibold text-text-primary">Acesso herdado</h2>@if($user->is_global_administrator)<p class="mt-3 text-sm text-text-secondary">Administrador global protegido, com bypass total independente de membro e cargo.</p>@else<div class="mt-5 grid gap-4">@forelse($churches as $church)<article class="rounded-2xl border border-border-default p-5"><h3 class="font-semibold text-text-primary">{{ $church->name }}</h3><p class="mt-2 text-sm text-text-secondary">Cargos: {{ $assignments->where('membership.church_id', $church->id)->map(fn($assignment) => $assignment->position->name.($assignment->position->department ? ' · '.$assignment->position->department->name : ''))->unique()->join(', ') }}</p><div class="mt-3 flex flex-wrap gap-2">@forelse(($effectivePermissions[$church->id] ?? []) as $module => $level)<span class="rounded-full bg-brand-primary-soft px-2.5 py-1 text-xs font-semibold text-brand-primary">{{ $module }} · {{ $level->value === 'write' ? 'escrita' : 'leitura' }}</span>@empty<span class="text-sm text-text-secondary">Nenhuma permissão configurada.</span>@endforelse</div></article>@empty<p class="mt-3 text-sm text-text-secondary">Nenhum cargo válido concede acesso no momento.</p>@endforelse</div>@endif</section>
@if(!$user->is_global_administrator)<div class="flex flex-wrap gap-3">@can('resetPassword', $user)<form method="POST" action="{{ route('users.password.reset', $user) }}" data-confirm="Gerar uma nova senha temporária? A senha atual deixará de funcionar.">@csrf<button class="ui-button-outline">Nova senha temporária</button></form>@endcan @can('forcePasswordChange', $user)<form method="POST" action="{{ route('users.password.force-change', $user) }}">@csrf @method('PATCH')<button class="ui-button-outline">Exigir troca de senha</button></form>@endcan @if($user->status === App\Status::Active)@can('inactivate', $user)<form method="POST" action="{{ route('users.inactivate', $user) }}" data-confirm="Inativar esta conta? As sessões abertas perderão o acesso.">@csrf @method('PATCH')<button class="ui-button-danger">Inativar</button></form>@endcan @else @can('activate', $user)<form method="POST" action="{{ route('users.activate', $user) }}">@csrf @method('PATCH')<button class="ui-button-primary">Ativar</button></form>@endcan @endif</div>@endif
</div>
@endsection
