@extends('layouts.app')
@section('title', 'Cargos e permissões')
@section('header', 'Cargos e permissões')
@section('content')
<div class="mx-auto grid max-w-7xl gap-7">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="ui-page-kicker">Administração</p><h1 class="mt-1 ui-page-title">Cargos e permissões</h1><p class="mt-2 ui-page-copy">Cargos representam funções reais dos membros; apenas os marcados podem conceder acesso.</p></div>@can('create', App\Models\Position::class)<a class="ui-button-primary" href="{{ route('positions.create') }}">Novo cargo</a>@endcan</header>
    <section class="ui-card overflow-hidden">
        <form class="grid gap-3 border-b border-border-default bg-surface-muted/60 p-5 sm:grid-cols-2 lg:grid-cols-[1fr_13rem_11rem_11rem_auto]" method="GET"><input class="ui-input" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Nome ou descrição" aria-label="Buscar cargo"><select class="ui-select" name="department_id" aria-label="Departamento"><option value="">Todos os departamentos</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(($filters['department_id'] ?? '') === $department->id)>{{ $department->name }}</option>@endforeach</select><select class="ui-select" name="status" aria-label="Status"><option value="">Todos os status</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Ativos</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inativos</option></select><select class="ui-select" name="grants_system_access" aria-label="Acesso ao sistema"><option value="">Todos</option><option value="1" @selected(($filters['grants_system_access'] ?? '') === '1')>Com acesso</option><option value="0" @selected(($filters['grants_system_access'] ?? '') === '0')>Sem acesso</option></select><button class="ui-button-primary">Filtrar</button></form>
        <div class="divide-y divide-border-default">@forelse($positions as $position)<article class="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_11rem_8rem_auto] lg:items-center"><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-semibold text-text-primary">{{ $position->name }}</h2>@if($position->fixed)<span class="rounded-full bg-surface-muted px-2.5 py-1 text-xs font-semibold text-text-secondary">Fixo</span>@endif @if($position->grants_system_access)<span class="rounded-full bg-info-soft px-2.5 py-1 text-xs font-semibold text-info">Concede acesso</span>@endif</div><p class="mt-1 text-sm text-text-secondary">{{ $position->department?->name ?? 'Sem departamento' }} · {{ $position->description ?: 'Sem descrição' }}</p></div><p class="text-sm text-text-secondary">{{ $position->assignments_count }} atribuições</p><x-status-badge :status="$position->status"/><div class="flex flex-wrap gap-2">@if(!$position->fixed)@can('update', $position)<a class="ui-button-outline px-3 py-2 text-xs" href="{{ route('positions.edit', $position) }}">Editar</a>@endcan @if($position->grants_system_access)@can('updatePermissions', $position)<a class="ui-button-secondary px-3 py-2 text-xs" href="{{ route('positions.permissions', $position) }}">Permissões</a>@endcan @endif @can('update', $position)<form method="POST" action="{{ route('positions.status', $position) }}" data-confirm="Alterar o status deste cargo? A mudança pode revogar acessos imediatamente.">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $position->status === App\Status::Active ? 'inactive' : 'active' }}"><input type="hidden" name="confirm_access_revocation" value="1"><button @class(['ui-button-danger px-3 py-2 text-xs' => $position->status === App\Status::Active, 'ui-button-secondary px-3 py-2 text-xs' => $position->status !== App\Status::Active])>{{ $position->status === App\Status::Active ? 'Inativar' : 'Ativar' }}</button></form>@endcan @endif</div></article>@empty<p class="p-12 text-center text-sm text-text-secondary">Nenhum cargo encontrado.</p>@endforelse</div><div class="p-4">{{ $positions->links() }}</div>
    </section>
</div>
@endsection
