@extends('layouts.app')
@section('title', 'Permissões do cargo')
@section('header', 'Permissões do cargo')
@section('content')
<div class="mx-auto grid max-w-6xl gap-6"><a class="text-sm font-semibold text-brand-primary" href="{{ route('positions.index') }}">← Voltar para cargos</a><header><p class="ui-page-kicker">Administração</p><h1 class="mt-1 ui-page-title">{{ $position->name }}</h1><p class="mt-2 ui-page-copy">Permissões herdadas por {{ $impact['users'] }} usuário(s), sempre dentro da igreja do vínculo ativo.</p></header>
@if($errors->any())<div class="ui-alert-error" role="alert"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="ui-card overflow-hidden" method="POST" action="{{ route('positions.permissions.update', $position) }}">@csrf @method('PUT')
    @foreach($modulesByCategory as $category => $modules)<section aria-labelledby="category-{{ Str::slug($category) }}"><h2 class="border-y border-border-default bg-surface-muted px-5 py-3 text-sm font-semibold tracking-wide text-text-secondary uppercase" id="category-{{ Str::slug($category) }}">{{ $category }}</h2>@foreach($modules as $module)@php($selected = old("permissions.{$module->id}", $levels[$module->id] ?? 'none'))<fieldset class="grid gap-4 border-b border-border-default p-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><legend class="sr-only">{{ $module->name }}</legend><div><h3 class="font-semibold text-text-primary">{{ $module->name }}</h3><p class="mt-1 text-sm text-text-secondary">{{ $module->description }}</p></div><div class="grid grid-cols-3 gap-2" role="radiogroup">@foreach(['none' => 'Sem acesso', 'read' => 'Leitura', 'write' => 'Escrita'] as $value => $label)<label class="cursor-pointer"><input class="peer sr-only" type="radio" name="permissions[{{ $module->id }}]" value="{{ $value }}" @checked($selected === $value)><span class="block rounded-xl border border-border-default px-3 py-2 text-center text-xs font-semibold text-text-secondary transition peer-checked:border-brand-primary peer-checked:bg-brand-primary-soft peer-checked:text-brand-primary">{{ $label }}</span></label>@endforeach</div></fieldset>@endforeach</section>@endforeach
    @if($impact['users'] > 0)<label class="m-5 flex items-start gap-3 rounded-2xl border border-warning/20 bg-warning-soft p-4"><input class="mt-1 size-4 accent-brand-primary" type="checkbox" name="confirm_access_revocation" value="1"><span class="text-sm text-warning">Confirmo alterações que possam revogar acesso de {{ $impact['users'] }} usuário(s).</span></label>@endif
    <div class="flex justify-end border-t border-border-default p-5"><button class="ui-button-primary">Salvar matriz</button></div>
</form></div>
@endsection
