@extends('layouts.app')
@section('title', 'Visão financeira')
@section('header', 'Visão financeira')
@section('content')
<div class="mx-auto grid max-w-7xl gap-7" data-financial-overview>
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="ui-page-kicker">Financeiro</p><h1 class="mt-1 ui-page-title">Visão financeira</h1><p class="mt-2 ui-page-copy">{{ $isConsolidated ? 'Consolidado de todas as áreas e igrejas.' : 'Indicadores de '.$overview['scope'].'.' }}</p></div><form method="GET"><label class="ui-label text-xs" for="year">Ano</label><select class="ui-select w-auto" id="year" name="year" onchange="this.form.submit()" data-autosize-select data-select-min-width="6" data-select-max-width="8">@for($option=today()->year-10;$option<=today()->year;$option++)<option value="{{ $option }}" @selected($year===$option)>{{ $option }}</option>@endfor</select></form></header>
    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Saldo consolidado',$overview['summary']['balance'],'text-brand-primary'],['Entradas no ano',$overview['summary']['inflows'],'text-success'],['Saídas no ano',$overview['summary']['outflows'],'text-danger'],['Resultado no ano',$overview['summary']['result'],$overview['summary']['result'] < 0 ? 'text-danger' : 'text-brand-primary']] as [$label,$value,$class])<article class="ui-card p-5"><p class="text-xs font-semibold tracking-wide text-text-secondary uppercase">{{ $label }}</p><p class="mt-2 text-2xl font-semibold {{ $class }}">R$ {{ number_format((float)$value,2,',','.') }}</p></article>@endforeach</section>
    <section class="grid gap-3 sm:grid-cols-2"><article class="ui-card p-5"><p class="text-xs font-semibold tracking-wide text-text-secondary uppercase">Pendências financeiras</p><p class="mt-2 text-2xl font-semibold text-warning">{{ $overview['pending']['count'] }} lançamentos</p></article><article class="ui-card p-5"><p class="text-xs font-semibold tracking-wide text-text-secondary uppercase">Valor pendente</p><p class="mt-2 text-2xl font-semibold text-warning">R$ {{ number_format((float)$overview['pending']['amount'],2,',','.') }}</p></article></section>
    @php $charts=[['monthly','Entradas × saídas por mês','Comparação mensal dos valores liquidados.'],['result','Resultado mensal','Entradas menos saídas em cada mês.'],['balance','Evolução do saldo','Saldo consolidado acumulado ao longo do ano.'],['income-categories','Entradas por categoria','Distribuição das receitas do período.'],['expense-categories','Despesas por categoria','Categorias com maior volume de saídas.'],['accounts','Recursos por conta','Saldo atual de cada caixa, banco ou carteira.'],['churches','Movimentação por igreja','Entradas, saídas e resultado por igreja.'],['departments','Gastos por departamento','Classificação gerencial das despesas.'],['annual','Comparativo anual','Resultado mensal do ano selecionado e do anterior.']]; @endphp
    <section class="grid gap-5 lg:grid-cols-2">@foreach($charts as [$key,$title,$copy])<article class="ui-card min-w-0 p-5 sm:p-6"><h2 class="font-semibold text-text-primary">{{ $title }}</h2><p class="mt-1 text-xs text-text-secondary">{{ $copy }}</p><div class="mt-4 h-80 w-full" data-chart="{{ $key }}" role="img" aria-label="{{ $title }}"></div></article>@endforeach</section>
    <script id="financial-overview-data" type="application/json">@json($overview)</script>
</div>
@endsection
